# -*- coding: utf-8 -*-
"""Plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cnbRbho0sBHlcTGlKQMkwNIQR4rk3Xc
"""

import matplotlib.pyplot as plt

def plot_model(data, title, cmap='viridis'):
    """
    Plots the model data as a 2D heatmap.

    Parameters:
        data (numpy.ndarray): The 2D array representing the model.
        title (str): The title of the plot.
        cmap (str): The colormap for the plot.
    """
    if data is None or data.size == 0:
        print("No data available to plot.")
        return

    plt.figure(figsize=(10, 6))
    plt.imshow(data, aspect='auto', cmap=cmap, origin='lower')
    plt.colorbar(label='Value')
    plt.title(title)
    plt.xlabel('Distance (km)')
    plt.ylabel('Depth (km)')
    plt.show()